version: '3'
services:
#  backend:
#    image: node:lts-stretch-slim
#    container_name: 'nembapi'
#    working_dir: /api
#    command: >
#      bash -c "yarn develop"
#    ports:
#      - "4000:4000"
#    volumes:
#      - ${PWD}:/api
#    depends_on:
#      - database

  database:
    image: mongo:latest
    container_name: 'nembapi_db'
    environment:
      - MONGO_INITDB_DATABASE=nembapi
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=toor
    volumes:
      - ./docker/db-data:/data/db
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    container_name: 'nembapi_db-gui'
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: toor
      ME_CONFIG_MONGODB_SERVER: database
      ME_CONFIG_MONGODB_AUTH_DATABASE: nembapi
      ME_CONFIG_MONGODB_AUTH_USERNAME: root
      ME_CONFIG_MONGODB_AUTH_PASSWORD: toor
    depends_on:
      - database
